int parser_parse_prog();
int parser_parse_func();
int parser_parse_params();
int parser_parse_params_next();
int parser_parse_body();
int parser_parse_cond();
int parser_parse_cond_else_block();
int parser_parse_loop();
int parser_parse_assign();
